### PR TITLE
Capture and use the dir where the init command is sourced

### LINKED ISSUE #32: Wrong builddir behavior
After working around #31:
```
$ pwd
/data/kergoth/mel/yocto-test/pyrex-test
$ PYREX_OEROOT=$PWD/oe-core PYREX_OEINIT=$PWD/oe-core/oe-init-build-env . ./pyrex/pyrex-init-build-env

### Shell environment set up for builds. ###

You can now run 'bitbake <target>'

Common targets are:
    core-image-minimal
    core-image-sato
    meta-toolchain
    meta-ide-support

You can also run generated qemu images with a command like 'runqemu qemux86'.

Other commonly useful commands are:
 - 'devtool' and 'recipetool' handle common recipe tasks
 - 'bitbake-layers' handles common layer tasks
 - 'oe-pkgdata-util' handles common target package tasks
$ pwd
/data/kergoth/mel/yocto-test/pyrex-test/build
$ which bitbake
bitbake is /data/kergoth/mel/yocto-test/pyrex-test/build/pyrex/bin/bitbake
$ bitbake -e | grep TOPDIR=
TOPDIR="/data/kergoth/mel/yocto-test/pyrex-test/oe-core/build"
$
```

Investigating further.

### PR DESCRIPTION
**Pull request by kergoth**
This fixes issues with relative build dir paths by ensuring we source
the init command from the same place both outside of docker and inside
of docker.

Close #32

### CODE REVIEW

File: docker/startup.sh [hunk 1]
```diff
@@ -19,8 +19,9 @@ declare -a COMMAND=("$@")
 # Consume all arguments before sourcing the environment script
 shift $#
 
-if [ -n "$PYREX_OEROOT" ] && [ -n "$PYREX_INIT_COMMAND" ]; then
-    pushd "$PYREX_OEROOT" > /dev/null
+PYREX_INIT_DIR="${PYREX_INIT_DIR:-$PYREX_OEROOT}"
```
Comment (JoshuaWatt) [inline docker/startup.sh]: I don't think there is any reason for this fallback. Pyrex will always provide the PYREX_INIT_DIR variable when invoking the container, so this can be removed.

File: pyrex.py [hunk 2]
```diff
@@ -477,6 +479,7 @@ def run(args):
                            '-e', 'PYREX_GID=%d' % gid,
                            '-e', 'PYREX_HOME=%s' % os.environ['HOME'],
                            '-e', 'PYREX_INIT_COMMAND=%s' % init_command,
+                           '-e', 'PYREX_INIT_DIR=%s' % init_dir,
                            '-e', 'PYREX_OEROOT=%s' % config['build']['oeroot'],
```
Comment (JoshuaWatt) [inline pyrex.py]: This variable is no longer used in the container, so it can be removed.

File: pyrex.py [hunk 3]
```diff
@@ -529,6 +532,7 @@ def run(args):
 
             env = os.environ.copy()
             env['PYREX_INIT_COMMAND'] = config['build']['initcommand']
+            env['PYREX_INIT_DIR'] = config['build']['initdir']
             env['PYREX_OEROOT'] = config['build']['oeroot']
```
Comment (JoshuaWatt) [inline pyrex.py]: This variable is no longer used and can be removed

**Comment by kergoth** [comment]
Updated with the 3 requested fixes. Interdiff with the changes (`git tbdiff origin/master kergoth/issue-32 issue-32`):
```diff
@@ -19,7 +19,6 @@
  
 -if [ -n "$PYREX_OEROOT" ] && [ -n "$PYREX_INIT_COMMAND" ]; then
 -    pushd "$PYREX_OEROOT" > /dev/null
-+PYREX_INIT_DIR="${PYREX_INIT_DIR:-$PYREX_OEROOT}"
 +if [ -n "$PYREX_INIT_DIR" ] && [ -n "$PYREX_INIT_COMMAND" ]; then
 +    pushd "$PYREX_INIT_DIR" > /dev/null
      source $PYREX_INIT_COMMAND > /dev/null
@@ -77,15 +76,17 @@
                             '-e', 'PYREX_GID=%d' % gid,
                             '-e', 'PYREX_HOME=%s' % os.environ['HOME'],
                             '-e', 'PYREX_INIT_COMMAND=%s' % init_command,
+-                           '-e', 'PYREX_OEROOT=%s' % config['build']['oeroot'],
 +                           '-e', 'PYREX_INIT_DIR=%s' % init_dir,
-                            '-e', 'PYREX_OEROOT=%s' % config['build']['oeroot'],
                             '-e', 'PYREX_CLEANUP_EXIT_WAIT',
                             '-e', 'PYREX_CLEANUP_LOG_FILE',
+                            '-e', 'PYREX_CLEANUP_LOG_LEVEL',
 @@
  
              env = os.environ.copy()
              env['PYREX_INIT_COMMAND'] = config['build']['initcommand']
+-            env['PYREX_OEROOT'] = config['build']['oeroot']
 +            env['PYREX_INIT_DIR'] = config['build']['initdir']
-             env['PYREX_OEROOT'] = config['build']['oeroot']
  
              stop_coverage()
+ 
```

**Comment by kergoth** [comment]
Thanks for the quick response on these.
